// Code generated by codegen. DO NOT EDIT.

package grammar_git_rebase

import (
	_ "embed"

	"github.com/lewtec/wazero-tree-sitter/grammar"
)

//go:embed grammar.wasm
var wasm []byte

// Language returns the wasm grammar for git_rebase.
func Language() *grammar.Language {
	return grammar.NewLanguage(wasm)
}

func init() {
	grammar.Register("git_rebase", Language())
}
