// Code generated by codegen. DO NOT EDIT.

package grammar_wgsl

import (
	_ "embed"

	"github.com/lewtec/wazero-tree-sitter/grammar"
)

//go:embed grammar.wasm
var wasm []byte

// Language returns the wasm grammar for wgsl.
func Language() *grammar.Language {
	return grammar.NewLanguage(wasm)
}

func init() {
	grammar.Register("wgsl", Language())
}
