package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// compileGrammar links tree-sitter core, the grammar, and runtime/shim.c
// into one standalone wasm module.
func compileGrammar(emcc, treeSitterPath string, unit GrammarUnit, wasmOut string) error {
	shim, err := findUp("runtime/shim.c")
	if err != nil {
		return err
	}
	langC, err := writeLangEntry(unit)
	if err != nil {
		return err
	}
	defer os.Remove(langC)

	args := []string{
		// -O0 keeps LLVM from blowing the GitHub runner's memory on large
		// parser.c files. -O2 would also run wasm-opt, and this emscripten's
		// binaryen is older than emcc expects.
		"-O0",
		"-std=c11",
		"-D_GNU_SOURCE",
		"-I" + filepath.Join(treeSitterPath, "lib", "include"),
		"-I" + filepath.Join(treeSitterPath, "lib", "src"),
		"-I" + filepath.Join(unit.Path, "src"),
		shim,
		langC,
		filepath.Join(treeSitterPath, "lib", "src", "lib.c"),
		unit.ParserC,
	}
	scanner := filepath.Join(unit.Path, "src", "scanner.c")
	if st, err := os.Stat(scanner); err == nil && !st.IsDir() {
		args = append(args, scanner)
	}
	if err := os.MkdirAll(filepath.Dir(wasmOut), 0o755); err != nil {
		return err
	}
	args = append(args,
		"-o", wasmOut,
		"-sSTANDALONE_WASM=1",
		"-sPURE_WASI=1",
		"-sALLOW_MEMORY_GROWTH=1",
		"-sSTACK_SIZE=1048576",
		"-sEXPORTED_FUNCTIONS=_malloc,_free,_wts_abi_version,_wts_node_sizeof,_wts_parser_new,_wts_parser_delete,_wts_parser_set_language,_wts_parser_parse,_wts_tree_delete,_wts_tree_root,_wts_node_is_null,_wts_node_type,_wts_node_child_count,_wts_node_child,_wts_node_field_name_for_child,_wts_node_named_child_count,_wts_node_named_child,_wts_node_start_byte,_wts_node_end_byte,_wts_node_is_named,_wts_node_is_extra,_wts_node_is_error,_wts_node_has_error,_wts_node_has_changes",
		"-sERROR_ON_UNDEFINED_SYMBOLS=0",
		"--no-entry",
	)
	cmd := emccCommand(emcc, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("emcc %s: %w", unit.Name, err)
	}
	return nil
}

// emccCommand runs emcc with the conda prefix Python.
// A `#!/usr/bin/env python3` shebang hits this machine's python3 shim
// (mise exec uv) which rejects `--` flags emcc passes through.
func emccCommand(emcc string, args ...string) *exec.Cmd {
	resolved := emcc
	if r, err := filepath.EvalSymlinks(emcc); err == nil {
		resolved = r
	}
	py, binDir := condaPython(resolved)
	// mise's .mise-bins/emcc is a shell launcher. Feeding that file to
	// Python is a syntax error. Only exec Python when the target is emcc.py.
	if py != "" && isPythonScript(resolved) {
		cmd := exec.Command(py, append([]string{resolved}, args...)...)
		cmd.Env = append(os.Environ(), "PATH="+binDir+string(os.PathListSeparator)+os.Getenv("PATH"))
		return cmd
	}
	cmd := exec.Command(emcc, args...)
	if binDir != "" {
		cmd.Env = append(os.Environ(), "PATH="+binDir+string(os.PathListSeparator)+os.Getenv("PATH"))
	}
	return cmd
}

func isPythonScript(path string) bool {
	if strings.HasSuffix(path, ".py") {
		return true
	}
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	buf := make([]byte, 80)
	n, _ := f.Read(buf)
	line := string(buf[:n])
	if i := strings.IndexByte(line, '\n'); i >= 0 {
		line = line[:i]
	}
	return strings.Contains(line, "python")
}

// condaPython finds prefix/bin/python3 by walking up from the emcc script.
func condaPython(emcc string) (python, binDir string) {
	dir := filepath.Dir(emcc)
	for range 6 {
		for _, cand := range []string{
			filepath.Join(dir, "bin", "python3"),
			filepath.Join(dir, "python3"),
		} {
			st, err := os.Stat(cand)
			if err == nil && !st.IsDir() {
				return cand, filepath.Dir(cand)
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", ""
}

func writeLangEntry(unit GrammarUnit) (string, error) {
	body := fmt.Sprintf(`#include <tree_sitter/api.h>
extern const TSLanguage *tree_sitter_%s(void);
const TSLanguage *wts_language(void) { return tree_sitter_%s(); }
`, unit.Name, unit.Name)
	f, err := os.CreateTemp("", "wts-lang-*.c")
	if err != nil {
		return "", err
	}
	if _, err := f.WriteString(body); err != nil {
		f.Close()
		return "", err
	}
	if err := f.Close(); err != nil {
		return "", err
	}
	return f.Name(), nil
}

func writeAPIWrapper(outputDir, grammarName string) error {
	dir := filepath.Join(outputDir, "grammar", grammarName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	src := fmt.Sprintf(`// Code generated by codegen. DO NOT EDIT.

package grammar_%s

import (
	_ "embed"

	"github.com/lewtec/wazero-tree-sitter/grammar"
)

//go:embed grammar.wasm
var wasm []byte

// Language returns the wasm grammar for %s.
func Language() *grammar.Language {
	return grammar.NewLanguage(wasm)
}

func init() {
	grammar.Register(%q, Language())
}
`, grammarName, grammarName, grammarName)
	return os.WriteFile(filepath.Join(dir, "api.go"), []byte(src), 0o644)
}

func findEmcc() (string, error) {
	if p := strings.TrimSpace(os.Getenv("EMCC")); p != "" {
		return p, nil
	}
	if p, err := exec.LookPath("emcc"); err == nil {
		return p, nil
	}
	out, err := exec.Command("mise", "which", "emcc").Output()
	if err != nil {
		return "", fmt.Errorf("emcc not on PATH (mise run codegen, or set EMCC): %w", err)
	}
	p := strings.TrimSpace(string(out))
	if p == "" {
		return "", fmt.Errorf("mise which emcc returned an empty path")
	}
	return p, nil
}

func findUp(rel string) (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := wd
	for {
		p := filepath.Join(dir, rel)
		if st, err := os.Stat(p); err == nil && !st.IsDir() {
			return p, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", fmt.Errorf("%s not found from %s", rel, wd)
}
