package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var onlyLangs []string

func main() {
	root := &cobra.Command{
		Use:   "codegen",
		Short: "Compile tree-sitter grammars to wasm with emscripten",
		RunE:  run,
	}
	root.Flags().StringSliceVar(&onlyLangs, "only", nil, "Limit to these language ids")
	root.AddCommand(&cobra.Command{
		Use:   "print-tree-sitter-path",
		Short: "Print the placed tree-sitter core path",
		RunE: func(cmd *cobra.Command, args []string) error {
			p, err := resolveTreeSitterPath()
			if err != nil {
				return err
			}
			fmt.Println(p)
			return nil
		},
	})
	if err := root.Execute(); err != nil {
		os.Exit(1)
	}
}

func run(cmd *cobra.Command, args []string) error {
	emcc, err := findEmcc()
	if err != nil {
		return err
	}
	tsPath, err := resolveTreeSitterPath()
	if err != nil {
		return err
	}
	units, err := discoverGrammarUnits("third-party/tree-sitter-*")
	if err != nil {
		return err
	}
	if len(onlyLangs) > 0 {
		want := map[string]bool{}
		for _, name := range onlyLangs {
			want[normalizeGrammarName(name)] = true
		}
		filtered := units[:0]
		for _, u := range units {
			if want[u.Name] {
				filtered = append(filtered, u)
			}
		}
		units = filtered
	}
	if len(units) == 0 {
		return fmt.Errorf("no grammar units under third-party/tree-sitter-*/src/parser.c; run mise run grammars:sync")
	}
	var failed int
	for _, unit := range units {
		wasmOut := filepath.Join("grammar", unit.Name, "grammar.wasm")
		fmt.Printf("compile %s\n", unit.Name)
		if err := compileGrammar(emcc, tsPath, unit, wasmOut); err != nil {
			fmt.Fprintf(os.Stderr, "%s: %v\n", unit.Name, err)
			failed++
			continue
		}
		if err := writeAPIWrapper(".", unit.Name); err != nil {
			return err
		}
		fmt.Printf("  %s\n", wasmOut)
	}
	if err := ensureGrammarModules("."); err != nil {
		return err
	}
	if err := updateLanguagesGo("."); err != nil {
		return err
	}
	if failed > 0 {
		fmt.Fprintf(os.Stderr, "%d/%d grammars failed\n", failed, len(units))
	}
	return nil
}

func updateLanguagesGo(outputDir string) error {
	langs, err := listGrammarLangs(filepath.Join(outputDir, "grammar"))
	if err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("// Code generated by codegen. DO NOT EDIT.\n\npackage main\n")
	if len(langs) > 0 {
		b.WriteString("\nimport (\n")
		for _, lang := range langs {
			fmt.Fprintf(&b, "\t_ %q\n", rootModulePath+"/grammar/"+lang)
		}
		b.WriteString(")\n")
	}
	return os.WriteFile(filepath.Join(outputDir, "cmd", "parse", "languages.go"), []byte(b.String()), 0o644)
}
